### ISSUE TITLE
Parenthesis after a method call that are not part of the method call break

### ISSUE THREAD

**Issue by tenderlove** [samphippen/rubyfmt#203]
* Ruby version: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
* Rubyfmt git sha: b4465434af9fbc9e131ccea7ed1130ac52249b1e

## Input file

```ruby
# frozen_string_literal: true

class CoolClass
  def cool_method
    other_cool_method (a + b).round(4)
  end
end
```

## Rubyfmt's output

```
Traceback (most recent call last):
	1: from /Users/aaron/git/rubyfmt/rubyfmt.rb:237:in `<main>'
/Users/aaron/git/rubyfmt/rubyfmt.rb:237:in `format_to_stdout': No variant matched untagged enum Expression. (Error from ripper_deserialize) (RuntimeError)
```

## This breaks because

It should probably not raise an exception on this input.

**Comment by tenderlove** [comment]
This input doesn't break:

```ruby
# frozen_string_literal: true

class CoolClass
  def cool_method
    other_cool_method((a + b).round(4))
  end
end
```
