### ISSUE TITLE
%{{#{}}} crashes rubyfmt

### ISSUE THREAD

**Issue by robotdana** [samphippen/rubyfmt#211]
I know that string looks horrible, but it a big graphql string tripped it and this is what i reduced it to. 

* Ruby version: 2.7.0 (also 2.6.5)
* Rubyfmt git sha: b2a96c54835b6f6f8801c9376127b20207a61ba9

## Input file

```ruby
puts %{{#{}}}
```

To break it there seems to need to be balanced parens of the same paren outside an interpolation.

other strings that break:
```ruby
%Q{a{#{}}}
%[[#{}]a]
%Q((#{}a))
```

## Rubyfmt's output:
```
Traceback (most recent call last):
        6: from /Users/dana/Projects/rubyfmt/rubyfmt.rb:235:in `<main>'
        5: from /Users/dana/Projects/rubyfmt/rubyfmt.rb:210:in `parse_file'
        4: from /Users/dana/Projects/rubyfmt/rubyfmt.rb:210:in `parse'
        3: from /Users/dana/Projects/rubyfmt/rubyfmt.rb:152:in `on_string_literal'
        2: from /Users/dana/Projects/rubyfmt/rubyfmt.rb:152:in `each'
        1: from /Users/dana/Projects/rubyfmt/rubyfmt.rb:156:in `block in on_string_literal'
/Users/dana/Projects/rubyfmt/rubyfmt.rb:156:in `eval': (eval):1: unterminated string meets end of file (SyntaxError)
```

## This breaks because

It forces me to make my string less horrifying with my very own hands

**Comment by robotdana** [comment]
Oh this is ruby, i'll see if i can fix it
