### ISSUE TITLE
Breaks on passing a method call to `return`

### ISSUE THREAD

**Issue by bquorning** [samphippen/rubyfmt#34]
* Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]`
* Rubyfmt git sha: cbc2e0edd23af6abc63659bd654e5580c4521571

## Input file

```ruby
return head :ok
```

## Rubyfmt's output

```
Traceback (most recent call last):
  7: from ../rubyfmt/src/rubyfmt.rb:2285:in `<main>'
  6: from ../rubyfmt/src/rubyfmt.rb:2282:in `main'
  5: from ../rubyfmt/src/rubyfmt.rb:2142:in `format_program'
  4: from ../rubyfmt/src/rubyfmt.rb:2142:in `each'
  3: from ../rubyfmt/src/rubyfmt.rb:2143:in `block in format_program'
  2: from ../rubyfmt/src/rubyfmt.rb:2136:in `format_expression'
  1: from ../rubyfmt/src/rubyfmt.rb:2056:in `block in format_expression'
../rubyfmt/src/rubyfmt.rb:1260:in `format_return': didn't get args add block to return (RuntimeError)
```

## This breaks because

Rubyfmt doesn’t understand that `head :ok` is evaluated first, and its result passed to `return`.

**Comment by samphippen** [comment]
this works now!

**Comment by bquorning** [comment]
Awesome, thank you!

**Comment by bquorning** [comment]
Actually no, it still doesn’t work

 - Ruby version: `ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]`
 - Rubyfmt git sha 96e49417897d61a8d0161e46a23635c2b1116ccb:

```
$ echo 'return head :ok' | ruby src/rubyfmt.rb
Traceback (most recent call last):
	7: from src/rubyfmt.rb:2352:in `<main>'
	6: from src/rubyfmt.rb:2349:in `main'
	5: from src/rubyfmt.rb:2199:in `format_program'
	4: from src/rubyfmt.rb:2199:in `each'
	3: from src/rubyfmt.rb:2200:in `block in format_program'
	2: from src/rubyfmt.rb:2193:in `format_expression'
	1: from src/rubyfmt.rb:2112:in `block in format_expression'
src/rubyfmt.rb:1289:in `format_return': didn't get args add block to return (RuntimeError)
```
