### ISSUE TITLE
Breaks on do;end stabby lambda in Ruby 2.6

### ISSUE THREAD

**Issue by bquorning** [samphippen/rubyfmt#47]
* Ruby version: `ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]`
* Rubyfmt git sha: 96e49417897d61a8d0161e46a23635c2b1116ccb

## Input file

```ruby
-> () do
end
```

## Rubyfmt's output

```
Traceback (most recent call last):
	14: from src/rubyfmt.rb:2352:in `<main>'
	13: from src/rubyfmt.rb:2349:in `main'
	12: from src/rubyfmt.rb:2199:in `format_program'
	11: from src/rubyfmt.rb:2199:in `each'
	10: from src/rubyfmt.rb:2200:in `block in format_program'
	 9: from src/rubyfmt.rb:2193:in `format_expression'
	 8: from src/rubyfmt.rb:2189:in `block in format_expression'
	 7: from src/rubyfmt.rb:2053:in `format_lambda'
	 6: from src/rubyfmt.rb:365:in `new_block'
	 5: from src/rubyfmt.rb:158:in `with_start_of_line'
	 4: from src/rubyfmt.rb:2054:in `block in format_lambda'
	 3: from src/rubyfmt.rb:2054:in `each'
	 2: from src/rubyfmt.rb:2055:in `block (2 levels) in format_lambda'
	 1: from src/rubyfmt.rb:2193:in `format_expression'
src/rubyfmt.rb:2193:in `fetch': key not found: "b" (KeyError)
```

**Comment by samphippen** [comment]
Closed by 537323f
