### ISSUE TITLE
Method calls using `::` instead of `.` are not recognized

### ISSUE THREAD

**Issue by bquorning** [samphippen/rubyfmt#61]
* Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]`
* Rubyfmt git sha: 05f7b5b0eb1a9192a034468acc99e9cbf1a00906

## Input file

```ruby
Nokogiri::XML "<p>"
```

## Rubyfmt's output

```
Traceback (most recent call last):
  9: from ./src/rubyfmt.rb:2444:in `<main>'
  8: from ./src/rubyfmt.rb:2441:in `main'
  7: from ./src/rubyfmt.rb:2286:in `format_program'
  6: from ./src/rubyfmt.rb:2286:in `each'
  5: from ./src/rubyfmt.rb:2287:in `block in format_program'
  4: from ./src/rubyfmt.rb:2280:in `format_expression'
  3: from ./src/rubyfmt.rb:2218:in `block in format_expression'
  2: from ./src/rubyfmt.rb:1053:in `format_command_call'
  1: from ./src/rubyfmt.rb:172:in `with_start_of_line'
./src/rubyfmt.rb:1055:in `block in format_command_call': got something other than a dot (RuntimeError)
```

## This breaks because

Method calls using `::` instead of `.` are not recognized by rubyfmt.

**Comment by samphippen** [comment]
huh, I thought I fixed this one.

**Comment by samphippen** [comment]
oh wait, all caps function, NM
