### ISSUE TITLE
Missing parentheses trips up rubyfmt

### ISSUE THREAD

**Issue by bquorning** [samphippen/rubyfmt#64]
* Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]`
* Rubyfmt git sha: 05f7b5b0eb1a9192a034468acc99e9cbf1a00906

This issue may be related to #63.

## Input file

```ruby
allow(Foo).to receive(:bar).and_return "baz"
```

## Rubyfmt's output

```
Traceback (most recent call last):
  11: from ./src/rubyfmt.rb:2444:in `<main>'
  10: from ./src/rubyfmt.rb:2441:in `main'
   9: from ./src/rubyfmt.rb:2286:in `format_program'
   8: from ./src/rubyfmt.rb:2286:in `each'
   7: from ./src/rubyfmt.rb:2287:in `block in format_program'
   6: from ./src/rubyfmt.rb:2280:in `format_expression'
   5: from ./src/rubyfmt.rb:2218:in `block in format_expression'
   4: from ./src/rubyfmt.rb:1053:in `format_command_call'
   3: from ./src/rubyfmt.rb:172:in `with_start_of_line'
   2: from ./src/rubyfmt.rb:1060:in `block in format_command_call'
   1: from ./src/rubyfmt.rb:2280:in `format_expression'
./src/rubyfmt.rb:2280:in `fetch': key not found: [:command_call, [:method_add_arg, [:fcall, [:@ident, "receive"... (KeyError)
```

## This breaks because

The missing parentheses around `"baz"` trips up rubyfmt.

**Comment by samphippen** [comment]
This is fixed.
