### ISSUE TITLE
Splat argument to `when` is not recognized

### ISSUE THREAD

**Issue by bquorning** [samphippen/rubyfmt#65]
* Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]`
* Rubyfmt git sha: 05f7b5b0eb1a9192a034468acc99e9cbf1a00906

## Input file

```ruby
case foo; when *bar; end
```

## Rubyfmt's output

```
Traceback (most recent call last):
  16: from ./src/rubyfmt.rb:2444:in `<main>'
  15: from ./src/rubyfmt.rb:2441:in `main'
  14: from ./src/rubyfmt.rb:2286:in `format_program'
  13: from ./src/rubyfmt.rb:2286:in `each'
  12: from ./src/rubyfmt.rb:2287:in `block in format_program'
  11: from ./src/rubyfmt.rb:2280:in `format_expression'
  10: from ./src/rubyfmt.rb:2260:in `block in format_expression'
   9: from ./src/rubyfmt.rb:1961:in `format_case'
   8: from ./src/rubyfmt.rb:1919:in `format_case_parts'
   7: from ./src/rubyfmt.rb:172:in `with_start_of_line'
   6: from ./src/rubyfmt.rb:1920:in `block in format_case_parts'
   5: from ./src/rubyfmt.rb:1069:in `format_list_like_thing_items'
   4: from ./src/rubyfmt.rb:1069:in `each_with_index'
   3: from ./src/rubyfmt.rb:1069:in `each'
   2: from ./src/rubyfmt.rb:1075:in `block in format_list_like_thing_items'
   1: from ./src/rubyfmt.rb:2280:in `format_expression'
./src/rubyfmt.rb:2280:in `fetch': key not found: "a" (KeyError)
```

## This breaks because

The splat argument `*bar` to `when` is not recognized by rubyfmt.

**Comment by bquorning** [comment]
Thank you 👍🏼
