### ISSUE TITLE
Fails with array containing two splats

### ISSUE THREAD

**Issue by twe4ked** [samphippen/rubyfmt#96]
* Ruby version: 2.5.1
* Rubyfmt git sha: de399cd09c50da975535ca27b974398576751421

## Input file

```ruby
[
  *[],
  *[],
]
```

## Rubyfmt's output

```
Traceback (most recent call last):
        18: from ./src/rubyfmt.rb:2557:in `<main>'
        17: from ./src/rubyfmt.rb:2554:in `main'
        16: from ./src/rubyfmt.rb:2397:in `format_program'
        15: from ./src/rubyfmt.rb:2397:in `each'
        14: from ./src/rubyfmt.rb:2398:in `block in format_program'
        13: from ./src/rubyfmt.rb:2391:in `format_expression'
        12: from ./src/rubyfmt.rb:2331:in `block in <main>'
        11: from ./src/rubyfmt.rb:1587:in `format_array'
        10: from ./src/rubyfmt.rb:1560:in `format_array_fast_path'
         9: from ./src/rubyfmt.rb:380:in `new_block'
         8: from ./src/rubyfmt.rb:171:in `with_start_of_line'
         7: from ./src/rubyfmt.rb:1561:in `block in format_array_fast_path'
         6: from ./src/rubyfmt.rb:1173:in `format_list_like_thing'
         5: from ./src/rubyfmt.rb:1141:in `format_list_like_thing_items'
         4: from ./src/rubyfmt.rb:1141:in `each_with_index'
         3: from ./src/rubyfmt.rb:1141:in `each'
         2: from ./src/rubyfmt.rb:1147:in `block in format_list_like_thing_items'
         1: from ./src/rubyfmt.rb:2391:in `format_expression'
./src/rubyfmt.rb:2391:in `fetch': key not found: "a" (KeyError)
```

## This breaks because

Possibly related to https://github.com/samphippen/rubyfmt/issues/93.

**Comment by twe4ked** [comment]
Thanks!
